import React from 'react';

interface ResultViewProps {
  imageSrc: string | null;
  analysisText: string;
  isStreaming: boolean;
  onReset: () => void;
}

const ResultView: React.FC<ResultViewProps> = ({ imageSrc, analysisText, isStreaming, onReset }) => {
  // Simple markdown parser for bold text and headers
  const renderMarkdown = (text: string) => {
    const lines = text.split('\n');
    return lines.map((line, idx) => {
      // Headers
      if (line.startsWith('### ')) {
        return <h3 key={idx} className="text-lg font-bold text-gray-800 mt-4 mb-2">{line.replace('### ', '')}</h3>;
      }
      if (line.startsWith('## ')) {
        return <h2 key={idx} className="text-xl font-bold text-brand-900 mt-6 mb-3">{line.replace('## ', '')}</h2>;
      }
      if (line.startsWith('# ')) {
        return <h1 key={idx} className="text-2xl font-bold text-brand-900 mt-6 mb-4">{line.replace('# ', '')}</h1>;
      }
      
      // Lists
      if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
         const content = line.trim().substring(2);
         // Handle bolding within list items
         const parts = content.split(/(\*\*.*?\*\*)/g);
         return (
            <li key={idx} className="ml-4 list-disc text-gray-700 mb-1">
                {parts.map((part, i) => {
                    if (part.startsWith('**') && part.endsWith('**')) {
                        return <strong key={i}>{part.slice(2, -2)}</strong>;
                    }
                    return part;
                })}
            </li>
         )
      }

      // Paragraphs with bolding
      const parts = line.split(/(\*\*.*?\*\*)/g);
      return (
        <p key={idx} className={`text-gray-700 leading-relaxed mb-2 ${line.trim() === '' ? 'h-2' : ''}`}>
          {parts.map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return <strong key={i} className="text-gray-900 font-semibold">{part.slice(2, -2)}</strong>;
            }
            return part;
          })}
        </p>
      );
    });
  };

  return (
    <div className="w-full max-w-4xl mx-auto animate-fade-in pb-12">
      <div className="bg-white rounded-xl shadow-xl overflow-hidden border border-gray-100">
        <div className="md:flex">
          {/* Image Side */}
          <div className="md:w-1/3 bg-gray-50 border-r border-gray-100 p-6 flex flex-col items-center justify-center">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Your Artwork</h3>
            {imageSrc && (
              <img 
                src={imageSrc} 
                alt="Analyzed Drawing" 
                className="w-full h-auto rounded-lg shadow-sm border border-gray-200 transform hover:scale-105 transition-transform duration-300" 
              />
            )}
            <button 
                onClick={onReset}
                className="mt-6 text-sm text-gray-500 hover:text-brand-600 underline"
            >
                Analyze Another
            </button>
          </div>

          {/* Text Side */}
          <div className="md:w-2/3 p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-2">HTP Insight</h2>
            <div className="h-1 w-12 bg-brand-500 rounded mb-6"></div>
            
            <div className="prose prose-sm md:prose-base max-w-none text-gray-600">
              {renderMarkdown(analysisText)}
              {isStreaming && (
                <span className="inline-block w-2 h-4 bg-brand-500 ml-1 animate-pulse"></span>
              )}
            </div>

            {!isStreaming && analysisText && (
               <div className="mt-8 p-4 bg-yellow-50 text-yellow-800 text-xs rounded-lg border border-yellow-100">
                  <strong>Disclaimer:</strong> This analysis is generated by AI for entertainment and self-reflection purposes only. It is not a professional psychological evaluation or medical diagnosis.
               </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultView;
